import { ArrowRight, ArrowUpRight, CarFront, MessageCircle } from "lucide-react";
import DealershipHero from "@/components/DealershipHero";
import VehicleCard from "@/components/VehicleCard";
import TradeInForm from "@/components/TradeInForm";
import { listVehicles } from "@/lib/dealership-db";
import { dealershipWhatsAppLink } from "@/lib/dealership-whatsapp";

const whatsappLink = dealershipWhatsAppLink("Olá! Gostaria de conversar com um vendedor sobre os veículos disponíveis.");

export default function DealershipHome() {
  const vehicles = listVehicles();
  const featuredVehicles = vehicles.filter((vehicle) => vehicle.featured);
  const selection = featuredVehicles.slice(0, 4);
  const offers = vehicles.filter((vehicle) => vehicle.promotionalPrice !== null).slice(0, 4);
  const cars = vehicles.filter((vehicle) => vehicle.type === "carro").slice(0, 4);
  const motorcycles = vehicles.filter((vehicle) => vehicle.type === "moto").slice(0, 4);

  return (
    <main className="min-h-screen bg-[#12130f] text-[#f8f8f4] selection:bg-[#c9f169] selection:text-[#171914]">
      <header className="absolute inset-x-0 top-0 z-30 border-b border-white/10 bg-[#12130f]/25 text-white backdrop-blur-sm">
        <div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between px-5 md:px-10">
          <a href="#inicio" className="flex items-center gap-2 text-lg font-black tracking-[0.1em]" aria-label="Motora, início"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#c9f169] text-[#171914]"><CarFront size={19} /></span>MOTORA<span className="text-[#c9f169]">.</span></a>
          <nav className="hidden items-center gap-7 text-xs font-semibold text-white/70 md:flex" aria-label="Navegação principal"><a href="#destaques" className="transition hover:text-[#c9f169]">Destaques</a><a href="/veiculos?type=carro" className="transition hover:text-[#c9f169]">Carros</a><a href="/veiculos?type=moto" className="transition hover:text-[#c9f169]">Motos</a><a href="#financiamento" className="transition hover:text-[#c9f169]">Financiamento</a><a href="#troca" className="transition hover:text-[#c9f169]">Avalie seu usado</a></nav>
          <a href="/veiculos" className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[#c9f169] px-4 text-xs font-bold text-[#171914] transition hover:bg-white">Ver estoque<ArrowUpRight size={14} /></a>
        </div>
      </header>

      <DealershipHero vehicleCount={vehicles.length} whatsappHref={whatsappLink} />

      <section id="destaques" className="scroll-mt-5 px-5 py-16 md:px-10 md:py-24"><div className="mx-auto max-w-[1360px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#c9f169]">Escolha da equipe</p><h2 className="mt-3 max-w-[600px] text-3xl font-semibold tracking-tight md:text-5xl">Veículos em destaque.</h2><p className="mt-3 text-sm text-white/50">{featuredVehicles.length ? "Seleção definida pela concessionária." : "Os destaques serão definidos pela concessionária."}</p></div><a href="/veiculos" className="inline-flex items-center gap-2 text-xs font-semibold text-white/70 hover:text-[#c9f169]">Ver todo o estoque<ArrowRight size={15} /></a></div>{selection.length ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{selection.map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} />)}</div> : <div className="mt-8 border border-white/10 bg-[#1a1b16] px-6 py-10"><h3 className="text-lg font-semibold">Novidades em preparação.</h3><p className="mt-2 max-w-[550px] text-sm leading-6 text-white/50">Quando a concessionária cadastrar e destacar um veículo no painel, ele aparecerá aqui automaticamente.</p><a href="/veiculos" className="mt-5 inline-flex min-h-10 items-center border border-white/25 px-4 text-xs font-semibold hover:border-white">Consultar estoque <ArrowRight size={14} className="ml-2" /></a></div>}{offers.length > 0 && <div className="mt-14 border-t border-white/10 pt-9"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#c9f169]">Preço promocional cadastrado</p><h3 className="mt-2 text-2xl font-semibold tracking-tight md:text-3xl">Ofertas da concessionária.</h3></div><a href="/veiculos" className="shrink-0 text-xs font-semibold text-white/65 hover:text-[#c9f169]">Ver estoque <ArrowRight size={14} className="ml-1 inline" /></a></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{offers.map((vehicle) => <VehicleCard key={`offer-${vehicle.id}`} vehicle={vehicle} />)}</div></div>}</div></section>

      <section id="carros" className="scroll-mt-5 border-y border-white/[0.07] bg-[#181914] px-5 py-16 md:px-10 md:py-20"><div className="mx-auto max-w-[1360px]"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-white/45">Automóveis</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Carros disponíveis.</h2></div><a href="/veiculos?type=carro" className="shrink-0 text-xs font-semibold text-[#c9f169]">Ver carros <ArrowRight size={14} className="ml-1 inline" /></a></div>{cars.length ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cars.map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} />)}</div> : <p className="mt-6 border-t border-white/10 pt-5 text-sm text-white/45">No momento, não há carros cadastrados no estoque.</p>}</div></section>

      <section id="motos" className="scroll-mt-5 px-5 py-16 md:px-10 md:py-20"><div className="mx-auto max-w-[1360px]"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-white/45">Duas rodas</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Motos disponíveis.</h2></div><a href="/veiculos?type=moto" className="shrink-0 text-xs font-semibold text-[#c9f169]">Ver motos <ArrowRight size={14} className="ml-1 inline" /></a></div>{motorcycles.length ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{motorcycles.map((vehicle) => <VehicleCard key={vehicle.id} vehicle={vehicle} />)}</div> : <p className="mt-6 border-t border-white/10 pt-5 text-sm text-white/45">No momento, não há motos cadastradas no estoque.</p>}</div></section>

      <section id="financiamento" className="scroll-mt-5 bg-[#20221c] px-5 py-16 md:px-10 md:py-20"><div className="mx-auto grid max-w-[1360px] gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#c9f169]">Planejamento claro</p><h2 className="mt-3 max-w-[700px] text-3xl font-semibold leading-tight tracking-tight md:text-5xl">Simulação de financiamento, sem promessas vazias.</h2><p className="mt-4 max-w-[640px] text-sm leading-7 text-white/55">Confira veículos com simulação habilitada pelo administrador. As parcelas são estimativas, não representam aprovação de crédito nem integração com bancos.</p></div><a href="/veiculos" className="inline-flex min-h-12 items-center justify-center gap-2 border border-[#c9f169]/55 px-5 text-xs font-semibold text-[#d5f78b] transition hover:bg-[#c9f169] hover:text-[#171914]">Encontrar veículos<ArrowRight size={15} /></a></div></section>

      <section className="px-5 py-16 md:px-10 md:py-20"><div className="mx-auto max-w-[1360px]"><TradeInForm /></div></section>

      <section className="border-y border-white/10 bg-[#c9f169] px-5 py-12 text-[#171914] md:px-10 md:py-14"><div className="mx-auto flex max-w-[1360px] flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#475530]">Atendimento direto</p><h2 className="mt-2 max-w-[680px] text-3xl font-semibold leading-tight tracking-tight">Seu próximo veículo começa com uma conversa.</h2></div>{whatsappLink ? <a href={whatsappLink} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-2 rounded-full bg-[#171914] px-6 text-xs font-bold text-white transition hover:bg-white hover:text-[#171914]"><MessageCircle size={17} />Chamar no WhatsApp<ArrowUpRight size={15} /></a> : <p className="max-w-[280px] text-xs leading-5 text-[#475530]">Configure o WhatsApp oficial para habilitar o atendimento direto.</p>}</div></section>

      <footer className="px-5 py-8 md:px-10"><div className="mx-auto flex max-w-[1360px] flex-col justify-between gap-4 text-[10px] text-white/40 sm:flex-row sm:items-center"><a href="#inicio" className="w-fit text-sm font-black tracking-[0.13em] text-white">MOTORA<span className="text-[#c9f169]">.</span></a><nav className="flex flex-wrap gap-x-5 gap-y-2" aria-label="Links do rodapé"><a href="/veiculos" className="hover:text-white">Estoque</a><a href="/veiculos?condition=novo" className="hover:text-white">Novos</a><a href="/veiculos?condition=seminovo" className="hover:text-white">Seminovos</a><a href="#troca" className="hover:text-white">Avaliação de troca</a><a href="/privacy-policy" className="hover:text-white">Privacidade</a><a href="/terms-of-service" className="hover:text-white">Termos</a><a href="/admin" className="hover:text-white">Área do administrador</a></nav><span>© {new Date().getFullYear()} · Consulte condições com a concessionária.</span></div></footer>

    </main>
  );
}
